site_name: è”¡å¤§é¹¿çš„ç¬”è®°æœ¬

theme:
  name: material # å›ºå®š
  language: zh # è¯­è¨€è®¾ç½®ä¸ºä¸­æ–‡(ä¼šæ”¹å˜æœç´¢æ /æœ€åä¿®æ”¹ ç­‰æ–‡å­—)ï¼Œé»˜è®¤ä¸ºè‹±æ–‡
  # logo: assets/logo.jpg # é¡µé¢ä¸­é¡¶éƒ¨æ å·¦ä¾§å›¾æ ‡
  favicon: icons/favicon.png # æµè§ˆå™¨é¡µé¢æ ‡ç­¾å›¾æ ‡
  font: false
  icon:
    logo: fontawesome/solid/book
  custom_dir: overrides # htmlæºä»£ç æ‰©å±•æ–‡ä»¶å¤¹
  features:
    - navigation.expand # ç›®å½•è‡ªåŠ¨å±•å¼€å­ç›®å½•
    # - toc.integrate # å³è¾¹çš„tocèåˆåˆ°å·¦ä¾§çš„ç›®å½•ä¸­
    - toc.follow # å³ä¾§tocéšç€é¡µé¢æ»‘åŠ¨è‡ªåŠ¨æ»‘åŠ¨
    - navigation.top # æœ‰å›åˆ°é¡µé¢æœ€ä¸Šæ–¹topçš„æŒ‰é”®
    - search.suggest # æœç´¢å»ºè®®
    - navigation.footer # é¡µé¢åº•éƒ¨æœ‰ä¸‹ä¸€é¡µçš„é“¾æ¥(æŒ‰ç›®å½•ä¸Šçš„é¡ºåº)
    - navigation.tabs # ä¸€çº§ç›®å½•èåˆè‡³é¡¶æ ï¼Œå¹¶ä¸”åªå±•ç¤ºäºŒçº§ç›®å½•
    - navigation.tracking # åœ¨ç¿»åˆ°é¡µé¢å¯¹åº”çš„æ ‡é¢˜å¤„æ—¶ï¼Œä¼šå°†åœ°å€æ çš„åœ°å€æ›´æ–°æˆæ ‡é¢˜å¤„çš„é“¾æ¥
    - navigation.instant
    - navigation.instant.progress # é¡µé¢é¡¶éƒ¨æ˜¾ç¤ºåŠ è½½è¿›åº¦æ¡
    - content.code.copy # ä»£ç å—å¤åˆ¶æŒ‰é”®
    - search.suggest # æœç´¢å»ºè®®
    - search.highlight # æœç´¢ç»“æœé«˜äº®/çªå‡ºæ˜¾ç¤º
    - search.share # æœç´¢ç»“æœåˆ†äº«
  palette: 

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: sunset glow
      toggle:
        icon: material/weather-night # å›¾æ ‡(å¯æ”¹ï¼Œä¸‹åŒ)
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: sunset glow dark
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - pymdownx.superfences: # mermaidç”»å›¾
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list # çŸ©å½¢æŒ‰é’®/æŒ‰é”®
  - def_list # a æ— åº/æœ‰åº/ä»»åŠ¡ åˆ—è¡¨
  - pymdownx.tasklist: # a
      custom_checkbox: true
  - pymdownx.critic # b Formatting å« é«˜äº®/åˆ é™¤çº¿/ä¸‹åˆ’çº¿/ä¸Šä¸‹è§’æ ‡ [ç­‰]
  - pymdownx.caret # b
  - pymdownx.keys # b
  - pymdownx.mark # b
  - pymdownx.tilde # b
  - toc: # ç›®å½•ç›¸å…³
      permalink: true # æ¯ä¸ªé¡µé¢å†…ï¼Œå„æ ‡é¢˜ä¼šç”Ÿæˆå„è‡ªçš„é“¾æ¥
      # title: ç›®å½• # ä¿®æ”¹é¡µé¢å³ä¾§ Table of contents æ–‡å­—
  - footnotes # è„šæ³¨
  - pymdownx.highlight: # c ä»£ç å—é…ç½®
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite # c
  - pymdownx.snippets # c
  - pymdownx.superfences # c
  - admonition # d æ ‡æ³¨
  - pymdownx.details # d
  - pymdownx.superfences # d
  - pymdownx.emoji: # ä½¿ç”¨emojiå’Œicon
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences # e å†…å®¹é€‰é¡¹å¡
  - pymdownx.tabbed: # e
      alternate_style: true 
  - md_in_html # åœ¨ md æ–‡æ¡£ä¸­èƒ½æ˜¾ç¤º html çš„æ•ˆæœ

# repo_name: caidalu/com
# repo_url: https://github.com/caidalu/com.git/

extra_javascript:
  - https://cdn.jsdelivr.net/gh/caidalu/com@main/docs/javascripts/katex.js 
  # - https://cdn.jsdelivr.net/gh/caidalu/com@main/docs/javascripts/katex.min.js  
  # - https://cdn.jsdelivr.net/gh/caidalu/com@main/docs/javascripts/auto-render.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  - https://cdn.jsdelivr.net/gh/caidalu/com@main/docs/javascripts/toc.js


extra_css:
  - https://cdn.jsdelivr.net/gh/caidalu/com@main/docs/stylesheets/katex.min.css
  - https://cdn.jsdelivr.net/gh/caidalu/com@main/docs/stylesheets/my_scheme.css
  - https://cdn.jsdelivr.net/gh/caidalu/com@main/docs/stylesheets/custom.css
  - https://cdn.jsdelivr.net/gh/caidalu/com@main/docs/stylesheets/roboto/roboto.css
  - https://cdn.jsdelivr.net/gh/caidalu/com@main/docs/stylesheets/card.css
  - https://cdn.jsdelivr.net/gh/caidalu/com@main/docs/stylesheets/fold_toc.css

extra:
  generator: false
  analytics:
    provider: google
    property: G-S82T9TYCJ4

# nav:
#   - Blog:
#     - index.md 

plugins:
  - blog: # è®¾ç½®blog
      blog_dir: . # è®¾ç½®blogå¯¹åº”çš„è·¯å¾„
      blog_toc: true # è®¾ç½®blogç´¢å¼•é¡µé¢çš„ç›®å½•
      post_date_format: full # è®¾ç½®blogç´¢å¼•é¡µé¢çš„æ—¥æœŸæ ¼å¼
      archive_toc: true
      categories_toc: true
      pagination_format: "$link_first $link_previous ~2~ $link_next $link_last" # è®¾ç½®blogç´¢å¼•é¡µé¢çš„åˆ†é¡µæ ¼å¼
      pagination_keep_content: true # è®¾ç½®blogç´¢å¼•é¡µé¢çš„åˆ†é¡µå†…å®¹
      draft_if_future_date: true # è®¾ç½®å¦‚æœblogçš„æ—¥æœŸæ˜¯æœªæ¥çš„è¯ï¼Œå°±ä¼šè¢«å½“æˆè‰ç¨¿ä¸ä¼šè¢«å‘å¸ƒ
  # - i18n: # è¯­è¨€åˆ‡æ¢ (éœ€è¦æ”¾åœ¨ git-revision-date-localized ä¹‹å‰)
  #   # v0.5.6
  #     # default_language: en
  #     # material_alternate: true
  #     # languages:
  #     #   zh:
  #     #     name: ç®€ä½“ä¸­æ–‡
  #     #     build: true
  #     #   en:
  #     #     name: English labels (è‹±æ–‡æ ‡ç­¾)
  #     #     build: false
  #   # v1.0.3
  #     reconfigure_search: false
  #     languages:
  #         - locale: zh
  #           name: ç®€ä½“ä¸­æ–‡
  #           build: true
  #           default: false
  #         - locale: en
  #           name: English labels (è‹±æ–‡æ ‡ç­¾)
  #           build: true
  #           default: true
  - git-revision-date-localized: # é¡µé¢ä¸‹æ–¹åˆ›å»ºå’Œä¿®æ”¹æ—¶é—´
      enable_creation_date: true
      type: timeago
  - glightbox # å›¾ç‰‡æ”¾å¤§
  - search: # æœç´¢(é€‰æ‹©æ”¯æŒä¸­æ–‡ã€è‹±æ–‡)
      separator: '[\u200b\u3000\-ã€ã€‚ï¼Œï¼ï¼Ÿï¼ï¼›\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
      # jieba_dict: jieba_dict/dict.txt.big
      # jieba_dict_user: jieba_dict/user_dict.txt
      lang: 
        # - zh
        - ja
        - en
  # - tags # æ·»åŠ ç»™å•ä¸ªæ–‡æ¡£æ·»åŠ tagæ ‡ç­¾
  - statistics: # ç»Ÿè®¡é¡µé¢å­—æ•°ã€ä»£ç è¡Œæ•°ã€é˜…è¯»æ—¶é—´
      page_read_time: false
      page_check_metadata: comments
      page_template: "page_template/page_statistics.html"


copyright: Copyright &copy; 2024 | ğŸ¨CaiDalu
